version: '3.9'

services:
  backend:
    build: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/code
    command: >
      bash -c "
        echo 'Waiting for MySQL to start...'
        while ! nc -z db 3306; do
          sleep 1
        done
        echo 'MySQL is up - starting Django'
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - PORT=4000
      - HOST=0.0.0.0
    networks:
      - app-network
    stdin_open: true
    tty: true
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_USER: django
      MYSQL_PASSWORD: demo
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
