version: '3.9'

services:
  backend:
    build: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/code
    command: >
      bash -c "
        echo 'Waiting for MySQL to start...'
        while ! nc -z db 3306; do
          sleep 1
        done
        echo 'MySQL is up - starting Django'
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    build: ./frontend
    container_name: react_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_USER: django
      MYSQL_PASSWORD: demo
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
